<a href="https://colab.research.google.com/github/mayaannkkk/FastAPI/blob/main/fastapi_ml_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
df = pd.read_csv('insurance.csv')

In [ ]:
df.head()

   age  weight  height  ...     city  occupation insurance_premium_category
0   67   119.8    1.56  ...   Jaipur     retired                       High
1   36   101.1    1.83  ...  Chennai  freelancer                        Low
2   39    56.8    1.64  ...   Indore  freelancer                        Low
3   22   109.4    1.55  ...   Mumbai     student                     Medium
4   69    62.2    1.60  ...   Indore     retired                       High

[5 rows x 8 columns]

In [ ]:
df_feat = df.copy()

In [ ]:
df_feat["bmi"] = df_feat["weight"] / (df_feat["height"] ** 2)

In [ ]:

# Feature 2: Age Group
def age_group(age):
    if age < 25:
        return "young"
    elif age < 45:
        return "adult"
    elif age < 60:
        return "middle_aged"
    return "senior"

In [ ]:
df_feat["age_group"] = df_feat["age"].apply(age_group)

In [ ]:
# Feature 3: Lifestyle Risk
def lifestyle_risk(row):
    if row["smoker"] and row["bmi"] > 30:
        return "high"
    elif row["smoker"] or row["bmi"] > 27:
        return "medium"
    else:
        return "low"


df_feat["lifestyle_risk"] = df_feat.apply(lifestyle_risk, axis=1)


tier_1_cities = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata", "Hyderabad", "Pune"]
tier_2_cities = [
    "Jaipur", "Chandigarh", "Indore", "Lucknow", "Patna", "Ranchi", "Visakhapatnam", "Coimbatore",
    "Bhopal", "Nagpur", "Vadodara", "Surat", "Rajkot", "Jodhpur", "Raipur", "Amritsar", "Varanasi",
    "Agra", "Dehradun", "Mysore", "Jabalpur", "Guwahati", "Thiruvananthapuram", "Ludhiana", "Nashik",
    "Allahabad", "Udaipur", "Aurangabad", "Hubli", "Belgaum", "Salem", "Vijayawada", "Tiruchirappalli",
    "Bhavnagar", "Gwalior", "Dhanbad", "Bareilly", "Aligarh", "Gaya", "Kozhikode", "Warangal",
    "Kolhapur", "Bilaspur", "Jalandhar", "Noida", "Guntur", "Asansol", "Siliguri"]

In [ ]:
# Feature 4: City Tier
def city_tier(city):
    if city in tier_1_cities:
        return 1
    elif city in tier_2_cities:
        return 2
    else:
        return 3

In [ ]:
df_feat['city_tier'] = df_feat["city"].apply(city_tier)

In [ ]:
df_feat.drop(columns=['age', 'weight', 'height', 'smoker', 'city'])[['income_lpa', 'occupation', 'bmi', 'age_group', 'lifestyle_risk', 'city_tier', 'insurance_premium_category']].sample(5)

    income_lpa   occupation  ...  city_tier insurance_premium_category
24       18.60  private_job  ...          2                     Medium
96       34.01  private_job  ...          1                        Low
49        2.29      student  ...          3                     Medium
48       32.69   unemployed  ...          1                     Medium
83        2.16      retired  ...          3                       High

[5 rows x 7 columns]

In [ ]:
# Select features and target
X = df_feat.drop('insurance_premium_category',axis=1)
y = df_feat["insurance_premium_category"]

In [ ]:
df_feat.head()

   age  weight  height  ...  age_group  lifestyle_risk city_tier
0   67   119.8    1.56  ...     senior          medium         2
1   36   101.1    1.83  ...      adult          medium         1
2   39    56.8    1.64  ...      adult             low         2
3   22   109.4    1.55  ...      young            high         1
4   69    62.2    1.60  ...     senior          medium         2

[5 rows x 12 columns]

In [ ]:
X_train, X_test,y_train,y_test = train_test_split(X, y , test_size=0.2, random_state=1)

In [ ]:
# Define categorical and numeric features
categorical_features = ["age_group", "lifestyle_risk", "occupation", "city_tier"]
numeric_features = ["bmi", "income_lpa"]


# Create column transformer for OHE
preprocessor = ColumnTransformer(transformers=[
        ("cat", OneHotEncoder(), categorical_features),
        ("num", "passthrough", numeric_features)
        ]
)

In [ ]:
# Create a pipeline with preprocessing and random forest classifier
pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(random_state=42))
])

In [ ]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  ['age_group',
                                                   'lifestyle_risk',
                                                   'occupation', 'city_tier']),
                                                 ('num', 'passthrough',
                                                  ['bmi', 'income_lpa'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [ ]:
# Predict and evaluate
y_pred = pipeline.predict(X_test)
accuracy_score(y_test, y_pred)

0.9

In [ ]:
import pickle

# Save the trained pipeline using pickle
pickle_model_path = "model.pkl"
with open(pickle_model_path, "wb") as f:
    pickle.dump(pipeline, f)

In [ ]:
import sklearn
print(sklearn.__version__)

1.6.1

In [ ]:
!pip show scikit-learn

Name: scikit-learn
Version: 1.6.1
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author:
Author-email:
License: BSD 3-Clause License

 Copyright (c) 2007-2024 The scikit-learn developers.
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 ----

 This binary distribution of scikit-learn also bundles the following software:

 ----

 Name: GCC runtime library
 Files: scikit_learn.libs/libgomp*.so*
 Availability: https://gcc.gnu.org/git/?p=gcc.git;a=tree;f=libgomp

 GCC RUNTIME LIBRARY EXCEPTION

 Version 3.1, 31 March 2009

 Copyright (C) 2009 Free Software Foundation, Inc. <http://fsf.org/>

 Everyone is permitted to copy and distribute verbatim copies of this
 license document, but changing it is not allowed.

 This GCC Runtime Library Exception ("Exception") is an additional
 permission under section 7 of the GNU General Public License, version
 3 ("GPLv3"). It applies to a given file (the "Runtime Library") that
 bears a notice placed by the copyright holder of the file stating that
 the file is governed by GPLv3 along with this Exception.

 When you use GCC to compile a program, GCC may combine portions of
 certain GCC header files and runtime libraries with the compiled
 program. The purpose of this Exception is to allow compilation of
 non-GPL (including proprietary) programs to use, in this way, the
 header files and runtime libraries covered by this Exception.

 0. Definitions.

 A file is an "Independent Module" if it either requires the Runtime
 Library for execution after a Compilation Process, or makes use of an
 interface provided by the Runtime Library, but is not otherwise based
 on the Runtime Library.

 "GCC" means a version of the GNU Compiler Collection, with or without
 modifications, governed by version 3 (or a specified later version) of
 the GNU General Public License (GPL) with the option of using any
 subsequent versions published by the FSF.

 "GPL-compatible Software" is software whose conditions of propagation,
 modification and use would permit combination with GCC in accord with
 the license of GCC.

 "Target Code" refers to output from any compiler for a real or virtual
 target processor architecture, in executable form or suitable for
 input to an assembler, loader, linker and/or execution
 phase. Notwithstanding that, Target Code does not include data in any
 format that is used as a compiler intermediate representation, or used
 for producing a compiler intermediate representation.

 The "Compilation Process" transforms code entirely represented in
 non-intermediate languages designed for human-written code, and/or in
 Java Virtual Machine byte code, into Target Code. Thus, for example,
 use of source code generators and preprocessors need not be considered
 part of the Compilation Process, since the Compilation Process can be
 understood as starting with the output of the generators or
 preprocessors.

 A Compilation Process is "Eligible" if it is done using GCC, alone or
 with other GPL-compatible software, or if it is done without using any
 work based on GCC. For example, using non-GPL-compatible Software to
 optimize any GCC intermediate representations would not qualify as an
 Eligible Compilation Process.

 1. Grant of Additional Permission.

 You have permission to propagate a work of Target Code formed by
 combining the Runtime Library with Independent Modules, even if such
 propagation would otherwise violate the terms of GPLv3, provided that
 all Target Code was generated by Eligible Compilation Processes. You
 may then convey such a combination under terms of your choice,
 consistent with the licensing of the Independent Modules.

 2. No Weakening of GCC Copyleft.

 The availability of this Exception does not imply any general
 presumption that third-party software is unaffected by the copyleft
 requirements of the license of GCC.

Location: /usr/local/lib/python3.12/dist-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: esda, fastai, hdbscan, imbalanced-learn, libpysal, librosa, mapclassify, mlxtend, pynndescent, pysal, segregation, sentence-transformers, shap, sklearn-compat, sklearn-pandas, spopt, spreg, tsfresh, umap-learn, yellowbrick